#pragma once

#include "types.hpp"
#include "utils/well_known_symbols.hpp"

// values
#include "values/shape.hpp"
#include "values/symbol.hpp"
#include "values/non_values.hpp"
#include "values/iterator.hpp"
#include "values/async_iterator.hpp"
#include "values/string.hpp"

#include "any_value.hpp"
#include "values/object.hpp"
#include "values/array.hpp"
#include "values/function.hpp"
#include "values/promise.hpp"
#include "values/descriptors.hpp"
#include "any_value_helpers.hpp"
#include "any_value_access.hpp"
#include "any_value_defines.hpp"
#include "library/error.hpp"
#include "exception_helpers.hpp"
#include "scheduler.hpp"

#include "values/prototypes/symbol.hpp"
#include "values/prototypes/object.hpp"
#include "values/prototypes/array.hpp"
#include "values/prototypes/function.hpp"
#include "values/prototypes/iterator.hpp"
#include "values/prototypes/async_iterator.hpp"
#include "values/prototypes/promise.hpp"
#include "values/prototypes/string.hpp"
#include "values/prototypes/number.hpp"

#include "values/helpers/symbol.hpp"
#include "values/helpers/object.hpp"
#include "values/helpers/array.hpp"
#include "values/helpers/function.hpp"
#include "values/helpers/iterator.hpp"
#include "values/helpers/async_iterator.hpp"
#include "values/helpers/promise.hpp"
#include "values/helpers/string.hpp"

// utilities
#include "utils/operators_primitive.hpp"
#include "utils/operators.hpp"
#include "utils/assignment_operators.hpp"
#include "utils/access.hpp"
#include "utils/log_any_value/log_any_value.hpp"

// js standard libraries
#include "library/symbol.hpp"
#include "library/process.hpp"
#include "library/function.hpp"
#include "library/console.hpp"
#include "library/performance.hpp"
#include "library/promise.hpp"
#include "library/math.hpp"
#include "library/object.hpp"
#include "library/array.hpp"
#include "library/global.hpp"
